//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Visual Studio.
//     Manual changes to this file may cause unexpected behavior.
//------------------------------------------------------------------------------

namespace WebApplication2
{


    public partial class BalanceEnquiry
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblCustomerID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCustomerID;

        /// <summary>
        /// lblAccountNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAccountNumber;

        /// <summary>
        /// lblCustomerName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCustomerName;

        /// <summary>
        /// lblAccountType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAccountType;

        /// <summary>
        /// lblAvailableBalance control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAvailableBalance;

        /// <summary>
        /// lblLedgerBalance control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblLedgerBalance;

        /// <summary>
        /// lblLastUpdated control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblLastUpdated;

        /// <summary>
        /// btnRefresh control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRefresh;
    }
}