//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Visual Studio.
//     Manual changes to this file may cause unexpected behavior.
//------------------------------------------------------------------------------

namespace WebApplication2
{


    public partial class MiniStatement1
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblCustomerID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCustomerID;

        /// <summary>
        /// lblAccountNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAccountNumber;

        /// <summary>
        /// btnRefresh control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRefresh;

        /// <summary>
        /// gvStatement control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvStatement;
    }
}